# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  TUgine_config = debug
endif
ifeq ($(config),release)
  TUgine_config = release
endif

PROJECTS := TUgine

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

TUgine:
ifneq (,$(TUgine_config))
	@echo "==== Building TUgine ($(TUgine_config)) ===="
	@${MAKE} --no-print-directory -C src -f Makefile config=$(TUgine_config)
endif

clean:
	@${MAKE} --no-print-directory -C src -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   TUgine"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"